### ISSUE TITLE
Thymeleaf-Version最新版本启动失败

### ISSUE THREAD

**Issue by xushen241994** [DimpleFeng/DimpleBlog#12]
1.QiNiuUtils类没有import com.google.gson.Gson;这个jar包
2.启动项目报：
org.quartz.JobPersistenceException: Couldn't retrieve trigger: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1538)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$12.execute(JobStoreSupport.java:1527)
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3800)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1524)
	at org.quartz.core.QuartzScheduler.getTrigger(QuartzScheduler.java:1505)
	at org.quartz.impl.StdScheduler.getTrigger(StdScheduler.java:508)
	at com.dimple.project.monitor.job.util.ScheduleUtils.getCronTrigger(ScheduleUtils.java:61)
	at com.dimple.project.monitor.job.service.JobServiceImpl.init(JobServiceImpl.java:43)

**Comment by skyls03** [comment]
@xushen241994 
1. gson包依赖
```xml
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.6</version>
</dependency>
```
2. 是因为你没有建表，导入项目中sql文件夹里的sql文件即可
3. 注意启动Redis
