### ISSUE TITLE
启动报错，请过目

### ISSUE THREAD

**Issue by H-P-C** [DimpleFeng/DimpleBlog#17]
起的是Thymeleaf-Version的版本，已配置好数据库，并执行sql，启动项目时报错，已确定数据库中有相应的表，不知道问题出在哪里。
____________________________________________
    _____
    /    )    ,                     /
---/----/---------_--_-------__----/-----__-
  /    /    /    / /  )    /   )  /    /___)
_/____/____/____/_/__/____/___/__/____(___ _
                         /
                        /
Spring Boot Version: 2.1.6.RELEASE
Project Version: V1.2
____________________________________________
2020-01-05 15:23:56.449  INFO 14816 -- [  restartedMain] com.dimple.DimpleBlogApplication         : Starting DimpleBlogApplication on DESKTOP-7JPBK5M with PID 14816 (E:\DimpleBlog\DimpleBlog\target\classes started by admin in E:\DimpleBlog\DimpleBlog)
2020-01-05 15:23:56.454 DEBUG 14816 -- [  restartedMain] com.dimple.DimpleBlogApplication         : Running with Spring Boot v2.1.6.RELEASE, Spring v5.1.8.RELEASE
2020-01-05 15:23:56.455  INFO 14816 -- [  restartedMain] com.dimple.DimpleBlogApplication         : The following profiles are active: druid
2020-01-05 15:24:01.210  INFO 14816 -- [  restartedMain] o.a.shiro.cache.ehcache.EhCacheManager   : Cache with name 'com.dimple.framework.shiro.realm.UserRealm.authorizationCache' does not yet exist.  Creating now.
2020-01-05 15:24:01.214  INFO 14816 -- [  restartedMain] o.a.shiro.cache.ehcache.EhCacheManager   : Added EhCache named [com.dimple.framework.shiro.realm.UserRealm.authorizationCache]
2020-01-05 15:24:02.780  INFO 14816 -- [  restartedMain] o.a.shiro.cache.ehcache.EhCacheManager   : Using existing EHCache named [loginRecordCache]
2020-01-05 15:24:04.921  INFO 14816 -- [  restartedMain] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-80"]
2020-01-05 15:24:04.938  INFO 14816 -- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-01-05 15:24:04.939  INFO 14816 -- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.21]
2020-01-05 15:24:05.200  INFO 14816 -- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-01-05 15:24:06.736 DEBUG 14816 -- [  restartedMain] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2020-01-05 15:24:07.436  INFO 14816 -- [  restartedMain] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-01-05 15:24:07.529  INFO 14816 -- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2020-01-05 15:24:07.555  INFO 14816 -- [  restartedMain] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2020-01-05 15:24:07.555  INFO 14816 -- [  restartedMain] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.1 created.
2020-01-05 15:24:07.561 DEBUG 14816 -- [  restartedMain] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2020-01-05 15:24:07.567  INFO 14816 -- [  restartedMain] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.1) 'DimpleScheduler' with instanceId 'DESKTOP-7JPBK5M1578209047531'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 20 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2020-01-05 15:24:07.567  INFO 14816 -- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'DimpleScheduler' initialized from an externally provided properties instance.
2020-01-05 15:24:07.567  INFO 14816 -- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.1
2020-01-05 15:24:07.570  INFO 14816 -- [  restartedMain] org.quartz.core.QuartzScheduler          : JobFactory set to: org.springframework.scheduling.quartz.AdaptableJobFactory@6f8746eb
2020-01-05 15:24:09.308  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  Spider
2020-01-05 15:24:09.308  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  SupportCategories
2020-01-05 15:24:09.309  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlogRanking
2020-01-05 15:24:09.309  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlogNewestUpdate
2020-01-05 15:24:09.309  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlogSupport
2020-01-05 15:24:09.309  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlogItem
2020-01-05 15:24:09.309  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  Tag
2020-01-05 15:24:09.310  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlacklistItem
2020-01-05 15:24:09.310  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BlacklistAll
2020-01-05 15:24:09.310  INFO 14816 -- [  restartedMain] com.dimple.framework.config.RedisConfig  : get cacheName  BaiduAccessToken
2020-01-05 15:24:09.409  INFO 14816 -- [  restartedMain] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2020-01-05 15:24:11.575  INFO 14816 -- [  restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-01-05 15:24:11.623  INFO 14816 -- [  restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-01-05 15:24:12.192  INFO 14816 -- [  restartedMain] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-01-05 15:24:12.603  INFO 14816 -- [  restartedMain] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-80"]
2020-01-05 15:24:12.668  INFO 14816 -- [  restartedMain] com.dimple.DimpleBlogApplication         : Started DimpleBlogApplication in 17.319 seconds (JVM running for 20.348)
2020-01-05 15:24:16.019 ERROR 14816 -- [impleScheduler]] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist

org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.initialize(JobStoreSupport.java:3920)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.schedulerStarted(JobStoreSupport.java:692)
	at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:539)
	at org.quartz.impl.StdScheduler.start(StdScheduler.java:142)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean$1.run(SchedulerFactoryBean.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 8 common frames omitted

2020-01-05 15:24:16.021  INFO 14816 -- [impleScheduler]] org.quartz.core.QuartzScheduler          : Scheduler DimpleScheduler_$_DESKTOP-7JPBK5M1578209047531 started.
2020-01-05 15:24:16.165 ERROR 14816 -- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted

2020-01-05 15:24:16.171 ERROR 14816 -- [SchedulerThread] org.quartz.core.ErrorLogger              : An error occurred while scanning for the next triggers to fire.

org.quartz.JobPersistenceException: Couldn't acquire next trigger: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2613)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2844)
	... 5 common frames omitted

2020-01-05 15:25:16.324 ERROR 14816 -- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted

2020-01-05 15:25:24.374 ERROR 14816 -- [_ClusterManager] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist

org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_LOCKS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted

2020-01-05 15:26:16.535 ERROR 14816 -- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'dimpleblog.QRTZ_TRIGGERS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted

Process finished with exit code -1

**Comment by DimpleFeng** [comment]
大概率是数据库表名的大小写问题,mysql配置的问题,百度一下就能解决...

**Comment by H-P-C** [comment]
> 大概率是数据库表名的大小写问题,mysql配置的问题,百度一下就能解决...

关键sql执行的是项目中的sql，而且表也不分大小写呀

**Comment by H-P-C** [comment]
> 大概率是数据库表名的大小写问题,mysql配置的问题,百度一下就能解决...

多谢回复。

**Comment by DimpleFeng** [comment]
看报错是这样原因,你需要设置数据库不区分大小写,你试试吧

**Comment by H-P-C** [comment]
> 看报错是这样原因,你需要设置数据库不区分大小写,你试试吧

好的，多谢您百忙之中做出回复！
